// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Yamb Online</title><script src=\"/js/htmx.min.js\"></script><!-- <script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js\"></script> --><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"flex items-center justify-center h-screen bg-gray-100\"><div class=\"bg-white shadow-lg rounded-xl p-6 w-full max-w-md space-y-4\"><h1 class=\"text-2xl font-bold text-center\">Yamb Online</h1><form hx-post=\"/create-room\" hx-target=\"#room-link\" class=\"space-y-4\"><div><label class=\"block text-sm font-medium\">Game Mode</label> <select name=\"mode\" class=\"mt-1 w-full border rounded-lg p-2\"><option value=\"1v1\">1 vs 1</option> <option value=\"2v2\">2 vs 2</option> <option value=\"1v1v1\">1 vs 1 vs 1</option></select></div><div><label class=\"block text-sm font-medium\">Dice Count</label> <select name=\"dice\" class=\"mt-1 w-full border rounded-lg p-2\"><option value=\"5\">5 Dice</option> <option value=\"6\">6 Dice</option></select></div><button type=\"submit\" class=\"w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600\">Create Room</button></form><div id=\"room-link\" class=\"text-center mt-4\"></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
