// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"bg-[var(--bg-game-panel)] border-t-2 border-[var(--border-primary)] px-6 py-3 flex-shrink-0\"><div class=\"flex flex-col sm:flex-row justify-between items-center gap-2 text-xs text-[var(--text-primary)]\"><div class=\"flex items-center gap-2\"><span class=\"font-medium\">Development:</span> <span>Stefan Novaković</span> <span class=\"text-[var(--border-primary)]\">|</span> <a href=\"https://nstefan002.github.io/\" target=\"_blank\" class=\"hover:text-[var(--border-primary)] transition-colors\">Website</a></div><div class=\"flex items-center gap-2\"><span class=\"font-medium\">Design:</span> <span>Marta Gavrilović</span> <span class=\"text-[var(--border-primary)]\">|</span> <a href=\"https://www.reddit.com/user/Skalamerijq/\" target=\"_blank\" class=\"hover:text-[var(--border-primary)] transition-colors\">Reddit Page</a></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
